apiVersion: v1
kind: Namespace
metadata:
  name: backend

---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend

---
apiVersion: v1
kind: Pod
metadata:
  name: debug-n
  namespace: frontend
  labels:
    appType: UI
spec:
  containers:
    - name: debug
      image: rkalluru/debug

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-np
  namespace: backend
  labels:
    appType: API
spec:
  containers:
    - name: nginx
      image: docker.io/nginx