apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    project: demo

---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    project: demo

---
apiVersion: v1
kind: Pod
metadata:
  name: debug-n
  namespace: frontend
  labels:
    appType: UI
spec:
  containers:
    - name: debug
      image: rkalluru/debug

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-np
  namespace: backend
  labels:
    appType: API
spec:
  containers:
    - name: nginx
      image: docker.io/nginx
---
apiVersion: v1
kind: NetworkPolicy
metadata:
  name: allow-only-frontend
  namespace: backend
spec:
  podSelector:
    matchLabels:
      appType: API
  namespaceSelector:
    matchLabels:
      project: demo
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          appType: UI
    ports:
    - protocol: TCP
      port: 80
  engress:
  - {}
          
     
      