apiVersion: v1
kind: ServiceAccount
metadata:
  name: debug
  namespace: default
---

apiVersion: v1
kind: Pod
metadata:
  name: debug01
  namespace: default
spec:
  serviceAccountName: debug
  containers:
    - name: debug
      image: rkalluru/debug

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader-R
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","watch","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-RB
  namespace: default
roleRef:
  kind: Role
  name: pod-reader-R
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: debug
    namespace: default
