apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
data:
  CATALOGUE_HOST: catalogue-ip
  CATALOGUE_PORT: catalogue-port
  USER_HOST: user-host
  USER_PORT: user-port
  CART_HOST: cart-host
  CART_PORT: cart-port
  SHIPPING_HOST: shipping-host
  SHIPPING_PORT: shipping-port
  PAYMENT_HOST: payment-host
  PAYMENT_PORT: payment-port
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-service-cm
data:
  catalogue.service: |
    [Unit]
    Description = Catalogue Service
    
    [Service]
    User=roboshop
    Environment=MONGO=true
    Environment=MONGO_URL="mongodb://<MONGODB-SERVER-IPADDRESS>:27017/catalogue"
    ExecStart=/bin/node /app/server.js
    SyslogIdentifier=catalogue
    
    [Install]
    WantedBy=multi-user.target
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-cm
data:
  MONGO: "true"
  MONGO_URL: mongodb://mongo-ip:27017/catalogue
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-cm
data:
  MONGO: "true"
  MONGO_URL: mongodb://mongo-ip:27017/catalogue
  REDIS_URL: redis://redis-ip:6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-cm
data:
  CATALOGUE_HOST: catalogue-ip
  CATALOGUE_PORT: catalogue-port
  REDIS_URL: redis://redis-ip:6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-cm
data:
  CART_ENDPOINT: cart-ip:cart-port
  DB_HOST: mysql-ip
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-cm
data:
  CART_HOST: cart-ip
  CART_PORT: "8080"
  USER_HOST: user-ip
  USER_PORT: "8080"
  AMQP_HOST: rabbitmq-ip
  AMQP_USER: roboshop
  AMQP_PASS: roboshop123
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-secreate
data:
  password: "YWJjZEAxMjM0"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    app: catalogue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    app: shipping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    app: shipping
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volume:
    - name: config-volume
      configMap:
        name: catalogue-service-cm
      env:
        - name: password
          valuesFrom:
            secretKeyRef:
              name: sample-secreate
              key: password
        - name: CATALOGUE_HOST
          valuesFrom:
            configMapKeyRef:
              name: frontend-cm
              key: CATALOGUE_HOST
        - name: CATALOGUE_PORT
          valuesFrom:
            configMapKeyRef:
              name: frontend-cm
              key: CATALOGUE_PORT
        - name: USER_HOST
          valuesFrom:
            configMapKeyRef:
              name: frontend-cm
              key: USER_HOST
        - name: USER_PORT
          valuesFrom:
            configMapKeyRef:
              name: frontend-cm
              key: USER_PORT
        - name: CART_HOST
          valuesFrom:
            configMapKeyRef:
              name: frontend-cm
              key: CART_HOST
        - name: CART_PORT
          valuesFrom:
            configMapKeyRef:
              name: frontend-cm
              key: CART_PORT
        - name: SHIPPING_HOST
          valuesFrom:
            configMapKeyRef:
              name: frontend-cm
              key: SHIPPING_HOST
        - name: SHIPPING_PORT
          valuesFrom:
            configMapKeyRef:
              name: frontend-cm
              key: SHIPPING_PORT
        - name: PAYMENT_HOST
          valuesFrom:
            configMapKeyRef:
              name: frontend-cm
              key: PAYMENT_HOST
        - name: PAYMENT_PORT
          valuesFrom:
            configMapKeyRef:
              name: frontend-cm
              key: PAYMENT_PORT
---
apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  containers:
    - name: catalogue
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/catalogue
      envFrom:
        configMapRef:
          name: catalogue-cm
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    app: cart
spec:
  containers:
    - name: cart
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/cart
      envFrom:
        configMapRef:
          name: cart-cm
---
apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  containers:
    - name: shipping
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
      envFrom:
        configMapRef:
          name: shipping-cm
---
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    app: user
spec:
  containers:
    - name: user
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/user
      envFrom:
        configMapRef:
          name: user-cm
---
apiVersion: v1
kind: Pod
metadata:
  name: payment
  labels:
    app: payment
spec:
  containers:
    - name: payment
      image: public.ecr.aws/w8x4g9h7/roboshop-v3/payment
      envFrom:
        configMapRef:
          name: payment-cm
