- name: Jenkins setup
  when: skip_install | bool # send variable skip_install=true
  block:
  - name: Create directory
    ansible.builtin.file:
      path: /var/lib/jenkins/init.groovy.d
      state: directory
      owner: jenkins
      group: jenkins
  - name: Copy files from template
    ansible.builtin.template:
      src: "{{ item }}"
      dest: /var/lib/jenkins/init.groovy.d/{{ item }}
      owner: jenkins
      group: jenkins
    loop:
      - 01-jenkines-plugins.groovy
      - mbranch.xml
      - shared-library.groovy


- name: Create jobs block
  when: create_job | bool # send variable create_job=true
  ansible.builtin.include_tasks:
    file: mbranch-job.yaml
  loop:
    - {jobName: 'test-1'}
    

  
