name: Provision Tool Infra
on: [workflow_dispatch]
jobs:
  Provision:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: set path
        run: export PATH=$PATH:/usr/local/bin:/usr/bin
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
        
